# Config File

gtf_file:
  /home/groups/hoolock2/myfile.gtf

bismark_ref_genome:
  /home/groups/hoolock2/u0/genomes/ensembl/homo_sapiens/primary_assembly

comparisons: ['ControlPre_V_ControlPost','PatientPre_V_PatientPost','PatientPre_V_ControlPre','PatientPost_V_ControlPost']

################################

#      IDE Configuration       #

################################

minimum_coverage:
  10

header_present:
  FALSE

processors:
  8

plots:
  0

tables:
  0

all:
  1
